name: "Calculator CI"

on:
    push:
        branches:
            - master
            - main
    workflow_dispatch:

jobs:
    sampleJob:
        runs-on: ubuntu-latest

        steps:
            - name: "setup python"
              uses: actions/setup-python@v5
              with:
                 python-version: "3.12.3"

            - name: "list files"
              run: ls -a

            - name: "Clone the repo"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: pip install -r requirements.txt

            - name: "Run tests"
              run: |
                    python -m pytest tests/